# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The OME Blog
tagline:          'A Jekyll theme'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://openmicroscopy.org

author:
  name:           'The OME Team'
  url:            https://twitter.com/openmicroscopy

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ome/blog
