# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The OME Blog
tagline:          'Microscopy, Life sciences imaging, and you'
description:      'The <a href="http://openmicroscopy.org" target="_blank">Open Microscopy Environment</a> project blog.'
url:              http://openmicroscopy.org

author:
  name:           'The OME Team'
  url:            https://twitter.com/openmicroscopy

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ome/blog
